spring:
  devtools:
    livereload:
      port: 35729

  thymeleaf:
    cache: false

  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:mysql://localhost:3306/notes_app?useSSL=false
    username: iu
    password: iu1004

  ## Hibernate Properties
  jpa:
    database: h2 # 사용 데이터베이스 선택
    show-sql: true # API 호출시, SQL 문을 콘솔에 출력한다.
    hibernate:
      ddl-auto: update # DDL 정의시 데이터베이스의 고유 기능을 지정합니다.
    open-in-view: true
