# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# Creating a new Note using POST /api/notes API
POST http://localhost:8080/api/notes
Content-Type: application/json

{"title":  "My First Note", "content": "Spring Boot is Awesome."}

###


# Creating a new Note using POST /api/notes API
POST http://localhost:8080/api/notes
Content-Type: application/json

{"title":  "My Second Note", "content": "Building Rest APIs is fun."}

###


# Retrieving all Notes using GET /api/notes API
GET http://localhost:8080/api/notes
Accept: application/json

###


# Retrieving a single Note using GET /api/notes/{noteId} API
GET http://localhost:8080/api/notes/2
Accept: application/json

###


# Updating a Note using PUT /api/notes/{noteId} API
PUT http://localhost:8080/api/notes/2
Content-Type: application/json

{"title":  "This is My Second Note", "content": "Building Rest APIs in Spring Boot us fun."}

###


# Deleting a Note using DELETE /api/notes/{noteId} API
DELETE http://localhost:8080/api/notes/2
Accept: application/json

###

